; G-Code generated by Simplify3D(R) Version 3.1.0
; Sep 4, 2016 at 5:33:24 PM
; Settings Summary
;   processName,Process1
;   applyToModels,rectangularprismwithhole
;   profileName,Wanhao Duplicator 6
;   profileVersion,2016-08-10 08:00:00
;   baseProfile,
;   printMaterial,ABS
;   printQuality,Medium
;   printExtruders,
;   extruderName,Primary Extruder
;   extruderToolheadNumber,0
;   extruderDiameter,0.4
;   extruderAutoWidth,0
;   extruderWidth,0.4
;   extrusionMultiplier,1
;   extruderUseRetract,1
;   extruderRetractionDistance,1.5
;   extruderExtraRestartDistance,0
;   extruderRetractionZLift,0
;   extruderRetractionSpeed,2400
;   extruderUseCoasting,1
;   extruderCoastingDistance,0.2
;   extruderUseWipe,0
;   extruderWipeDistance,2
;   primaryExtruder,0
;   layerHeight,0.15
;   topSolidLayers,4
;   bottomSolidLayers,3
;   perimeterOutlines,2
;   printPerimetersInsideOut,1
;   startPointOption,2
;   startPointOriginX,0
;   startPointOriginY,0
;   startPointOriginZ,300
;   sequentialIslands,0
;   spiralVaseMode,0
;   firstLayerHeightPercentage,130
;   firstLayerWidthPercentage,100
;   firstLayerUnderspeed,0.3
;   useRaft,0
;   raftExtruder,0
;   raftLayers,3
;   raftOffset,3
;   raftSeparationDistance,0.14
;   raftInfill,85
;   disableRaftBaseLayers,0
;   useSkirt,1
;   skirtExtruder,0
;   skirtLayers,1
;   skirtOutlines,2
;   skirtOffset,4
;   usePrimePillar,0
;   primePillarExtruder,999
;   primePillarWidth,12
;   primePillarLocation,7
;   primePillarSpeedMultiplier,1
;   useOozeShield,0
;   oozeShieldExtruder,999
;   oozeShieldOffset,2
;   oozeShieldOutlines,1
;   oozeShieldSidewallShape,1
;   oozeShieldSidewallAngle,30
;   oozeShieldSpeedMultiplier,1
;   infillExtruder,0
;   internalInfillPattern,Rectilinear
;   externalInfillPattern,Rectilinear
;   infillPercentage,20
;   outlineOverlapPercentage,35
;   infillExtrusionWidthPercentage,125
;   minInfillLength,3
;   infillLayerInterval,1
;   infillAngles,45,-45
;   overlapInfillAngles,0
;   generateSupport,0
;   supportExtruder,0
;   supportInfillPercentage,30
;   supportExtraInflation,0
;   denseSupportLayers,0
;   denseSupportInfillPercentage,70
;   supportLayerInterval,1
;   supportHorizontalPartOffset,0.3
;   supportUpperSeparationLayers,1
;   supportLowerSeparationLayers,1
;   supportType,0
;   supportGridSpacing,4
;   maxOverhangAngle,45
;   supportAngles,0
;   temperatureName,Primary Extruder,Heated Build Platform
;   temperatureNumber,0,1
;   temperatureSetpointCount,1,1
;   temperatureSetpointLayers,1,1
;   temperatureSetpointTemperatures,230,100
;   temperatureStabilizeAtStartup,1,1
;   temperatureHeatedBed,0,1
;   temperatureRelayBetweenLayers,0,0
;   temperatureRelayBetweenLoops,0,0
;   fanLayers,1
;   fanSpeeds,0
;   blipFanToFullPower,1
;   adjustSpeedForCooling,1
;   minSpeedLayerTime,15
;   minCoolingSpeedSlowdown,20
;   increaseFanForCooling,1
;   minFanLayerTime,10
;   maxCoolingFanSpeed,30
;   increaseFanForBridging,1
;   bridgingFanSpeed,45
;   use5D,1
;   relativeEdistances,0
;   allowEaxisZeroing,1
;   independentExtruderAxes,0
;   includeM10123,0
;   stickySupport,1
;   applyToolheadOffsets,0
;   gcodeXoffset,0
;   gcodeYoffset,0
;   gcodeZoffset,0
;   overrideMachineDefinition,1
;   machineTypeOverride,0
;   strokeXoverride,200
;   strokeYoverride,200
;   strokeZoverride,175
;   originOffsetXoverride,0
;   originOffsetYoverride,0
;   originOffsetZoverride,0
;   homeXdirOverride,-1
;   homeYdirOverride,-1
;   homeZdirOverride,-1
;   flipXoverride,1
;   flipYoverride,-1
;   flipZoverride,1
;   toolheadOffsets,0,0|0,0|0,0|0,0|0,0|0,0
;   overrideFirmwareConfiguration,1
;   firmwareTypeOverride,RepRap (Marlin/Repetier/Sprinter)
;   GPXconfigOverride,r2
;   baudRateOverride,250000
;   overridePrinterModels,1
;   printerModelsOverride
;   startingGcode,G28 ; home all axes,G92 E0 ; zero the extruded length,G1 Z10 ; lower,G1 E20 F200 ; purge nozzle quickly,G1 E10 F60 ; purge nozzle slowly,G92 E0 ; zero the extruded length again,G1 E-1.5 F400 ; retract,G1 X170 Z0 F9000 ; pull away filament,G1 X180 F9000 ; wipe,G1 Y20 F9000 ; wipe,G1 E0 ; feed filament back
;   layerChangeGcode,
;   retractionGcode,
;   toolChangeGcode,
;   endingGcode,G28 X0 ; home the X-axis,M104 S0 ; turn off heaters,M140 S0 ; turn off bed,M84 ; disable motors
;   exportFileFormat,gcode
;   celebration,0
;   celebrationSong,Random Song
;   postProcessing,
;   defaultSpeed,2500
;   outlineUnderspeed,0.65
;   solidInfillUnderspeed,0.7
;   supportUnderspeed,0.7
;   rapidXYspeed,6000
;   rapidZspeed,1000
;   minBridgingArea,5
;   bridgingExtraInflation,0
;   bridgingExtrusionMultiplier,1
;   bridgingSpeedMultiplier,0.5
;   filamentDiameter,1.75
;   filamentPricePerKg,46
;   filamentDensity,1.25
;   useMinPrintHeight,0
;   minPrintHeight,0
;   useMaxPrintHeight,0
;   maxPrintHeight,0
;   useDiaphragm,0
;   diaphragmLayerInterval,20
;   robustSlicing,1
;   mergeAllIntoSolid,0
;   onlyRetractWhenCrossingOutline,1
;   retractBetweenLayers,0
;   useRetractionMinTravel,1
;   retractionMinTravel,0.02
;   retractWhileWiping,0
;   onlyWipeOutlines,1
;   avoidCrossingOutline,0
;   maxMovementDetourFactor,3
;   toolChangeRetractionDistance,12
;   toolChangeExtraRestartDistance,-0.5
;   toolChangeRetractionSpeed,600
;   allowThinWallGapFill,1
;   thinWallAllowedOverlapPercentage,10
;   horizontalSizeCompensation,0
G90
M82
M106 S0
M140 S100
M190 S100
M104 S230 T0
M109 S230 T0
G28 ; home all axes
G92 E0 ; zero the extruded length
G1 Z10 ; lower
G1 E20 F200 ; purge nozzle quickly
G1 E10 F60 ; purge nozzle slowly
G92 E0 ; zero the extruded length again
G1 E-1.5 F400 ; retract
G1 X170 Z0 F9000 ; pull away filament
G1 X180 F9000 ; wipe
G1 Y20 F9000 ; wipe
G1 E0 ; feed filament back
; layer end
G28 X0 ; home the X-axis
M104 S0 ; turn off heaters
M140 S0 ; turn off bed
M84 ; disable motors
; Build Summary
;   Build time: 0 hours 0 minutes
;   Filament length: 0.0 mm (0.00 m)
;   Plastic volume: 0.00 mm^3 (0.00 cc)
;   Plastic weight: 0.00 g (0.00 lb)
;   Material cost: 0.00
